FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci
COPY frontend/ .
ARG SHOPIFY_STORE_ID
ARG SHOPIFY_SHOP_DOMAIN
ARG SHOPIFY_CLIENT_ID
ARG SHOPIFY_OAUTH_REDIRECT_URI
ARG SHOPIFY_OAUTH_REDIRECT_URI_PROD
ARG SHOPIFY_API_VERSION
ARG SHOPIFY_APP_URL
ARG SHOPIFY_APP_URL_PROD
ARG SHOPIFY_BACKEND_URL
ARG SHOPIFY_BACKEND_URL_PROD
ENV SHOPIFY_STORE_ID=$SHOPIFY_STORE_ID
ENV SHOPIFY_SHOP_DOMAIN=$SHOPIFY_SHOP_DOMAIN
ENV SHOPIFY_CLIENT_ID=$SHOPIFY_CLIENT_ID
ENV SHOPIFY_OAUTH_REDIRECT_URI=$SHOPIFY_OAUTH_REDIRECT_URI
ENV SHOPIFY_OAUTH_REDIRECT_URI_PROD=$SHOPIFY_OAUTH_REDIRECT_URI_PROD
ENV SHOPIFY_API_VERSION=$SHOPIFY_API_VERSION
ENV SHOPIFY_APP_URL=$SHOPIFY_APP_URL
ENV SHOPIFY_APP_URL_PROD=$SHOPIFY_APP_URL_PROD
ENV SHOPIFY_BACKEND_URL=$SHOPIFY_BACKEND_URL
ENV SHOPIFY_BACKEND_URL_PROD=$SHOPIFY_BACKEND_URL_PROD
RUN npm run build

FROM node:20-alpine AS backend-builder
WORKDIR /app
COPY backend/package.json backend/package-lock.json* ./
RUN npm ci --omit=dev
COPY backend/ .

FROM node:20-alpine
RUN apk add --no-cache nginx
WORKDIR /app
COPY --from=frontend-builder /app/dist /app/frontend/dist
COPY --from=backend-builder /app /app/backend
COPY nginx-app.conf /etc/nginx/conf.d/shopify-account.conf
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh
ENV NODE_ENV=production
ENV PORT=3601
EXPOSE 80
CMD ["/app/start.sh"]
